### ISSUE TITLE
404 Not Found?

### ISSUE THREAD

**Issue by nesger** [MobileDevice/mobileDevice.github.io#1]
出现了404错误，没法访问？

<img width="704" alt="404" src="https://user-images.githubusercontent.com/17486963/32707110-3ba0b9b8-c7e7-11e7-9a76-fde7b0194c22.png">

**Comment by monsterLin** [comment]
@nesger 论坛受到了一波恶意流量的攻击，现在在维护中，最近会开放的，谢谢支持O(∩_∩)O哈哈~
